version: '3.1'

services:
  backend:
    build: backend
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env.dev
    restart: always
    networks:
      - mynet

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env.dev
    ports:
      - '5432:5432'
    networks:
      - mynet
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  mynet: